# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

persistence_curve <- function(T) {
    .Call('trajcomp_persistence_curve', PACKAGE = 'trajcomp', T)
}

persistence_extrema <- function(T) {
    .Call('trajcomp_persistence_extrema', PACKAGE = 'trajcomp', T)
}

persistence_bars <- function(T, it = -1L) {
    .Call('trajcomp_persistence_bars', PACKAGE = 'trajcomp', T, it)
}

persistence_pruned <- function(T, Beta = 0L, it = -1L) {
    .Call('trajcomp_persistence_pruned', PACKAGE = 'trajcomp', T, Beta, it)
}

persistence_comps <- function(T, Beta = 0L, it = -1L) {
    .Call('trajcomp_persistence_comps', PACKAGE = 'trajcomp', T, Beta, it)
}

persistence_multires_index <- function(T, Beta = 0L, Levels = 5L) {
    .Call('trajcomp_persistence_multires_index', PACKAGE = 'trajcomp', T, Beta, Levels)
}

persistence_multires <- function(T, Beta = 0L, Levels = 5L) {
    .Call('trajcomp_persistence_multires', PACKAGE = 'trajcomp', T, Beta, Levels)
}

persistence_dist <- function(T, Beta = 0L, Epsilon = 5L, Iterations = 5L) {
    .Call('trajcomp_persistence_dist', PACKAGE = 'trajcomp', T, Beta, Epsilon, Iterations)
}

persistence_test_bars <- function(T, Beta = 0L, it = -1L) {
    .Call('trajcomp_persistence_test_bars', PACKAGE = 'trajcomp', T, Beta, it)
}

persistence_test_comps <- function(T, Beta = 0L, it = -1L) {
    .Call('trajcomp_persistence_test_comps', PACKAGE = 'trajcomp', T, Beta, it)
}

string_distance_dispatchbyname <- function(t, q, name, k) {
    .Call('trajcomp_string_distance_dispatchbyname', PACKAGE = 'trajcomp', t, q, name, k)
}

#' compiles a valid XML distance description into a handle
#' 
#' @param setting an XML string describing the distance to be used
#' @param setting an XML string describing the distance to be used
#' @return An integer handle to pass the (compiled) XML settings to other functions
#' @details
#' Distance functions are described via a specific XML format. Consider reading 
#' the documentation at \url{trajectorycomputing.com/libtrajcomp-xml} 
#' @export
compileSettings <- function(setting) {
    .Call('trajcomp_compileSettings', PACKAGE = 'trajcomp', setting)
}

trajectory_distances <- function(S, T, hSetting) {
    .Call('trajcomp_trajectory_distances', PACKAGE = 'trajcomp', S, T, hSetting)
}

trajectory_distance_vector <- function(S, T, hSetting) {
    .Call('trajcomp_trajectory_distance_vector', PACKAGE = 'trajcomp', S, T, hSetting)
}

encode <- function(T, feature) {
    .Call('trajcomp_encode', PACKAGE = 'trajcomp', T, feature)
}

distance_vector_ddply <- function(T, Q, hSetting) {
    .Call('trajcomp_distance_vector_ddply', PACKAGE = 'trajcomp', T, Q, hSetting)
}

getDistanceNames <- function(hSetting) {
    .Call('trajcomp_getDistanceNames', PACKAGE = 'trajcomp', hSetting)
}

DouglasPeucker <- function(S, epsilon = 0) {
    .Call('trajcomp_DouglasPeucker', PACKAGE = 'trajcomp', S, epsilon)
}

DouglasPeuckerWeights <- function(S, epsilon) {
    .Call('trajcomp_DouglasPeuckerWeights', PACKAGE = 'trajcomp', S, epsilon)
}

doPLI <- function(data, n) {
    .Call('trajcomp_doPLI', PACKAGE = 'trajcomp', data, n)
}

#' Clusters trajectories according to the TRACLUS framework
#' 
#' @param TrajectoryDB a trajectory database giving 2D trajectories split by NaN or NA
#' @param setting an XML string describing the distance to be used
#' @return An integer handle to pass the (compiled) XML settings to other functions
#' @details
#' Distance functions are described via a specific XML format. Consider reading 
#' the documentation at \url{trajectorycomputing.com/libtrajcomp-xml} 
#' @export
cpp_traclus <- function(TrajectoryDB, eps, minLines) {
    .Call('trajcomp_cpp_traclus', PACKAGE = 'trajcomp', TrajectoryDB, eps, minLines)
}

redSVD <- function(AA, num) {
    .Call('trajcomp_redSVD', PACKAGE = 'trajcomp', AA, num)
}

